//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrito
    {
        public int id_Carrito { get; set; }
        public Nullable<int> id_Cliente { get; set; }
        public Nullable<int> id_Producto { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
