//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Venta
    {
        public int id_DVenta { get; set; }
        public Nullable<int> id_Venta { get; set; }
        public Nullable<int> id_Producto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
